version: '3'

services:

  rabbitmq:
    container_name: rabbitmq-db
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      -'./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
